Repository stratis-storage/stratisd, pull requests merged in 2018-05, with the labels that each got.

#916 deps: update uuid to 0.6
  Cargo.lock
  Cargo.toml
Labels: review-final

#897 Move general startup tasks into main(), and ensure pidfile is held properly
  src/bin/stratisd.rs
Labels: review-final

#924 Update to new version of clippy
  .travis.yml
  Cargo.lock
Labels: in progress

#926 Allow failures for lint task on the Python code
  .travis.yml
Labels: in progress

#922 Organize wrappers for command-line invocations
  src/engine/strat_engine/thinpool/cmd.rs
  src/engine/strat_engine/thinpool/filesystem.rs
  src/engine/strat_engine/thinpool/mdv.rs
  src/engine/strat_engine/thinpool/mod.rs
  src/engine/strat_engine/thinpool/thinpool.rs
Labels: review-final

#930 Establish SyncAll trait for metadata testing
  src/engine/strat_engine/backstore/metadata.rs
Labels: review-final

#934 Pin dbus-python to 1.2.4
  .travis.yml
  tests/client-dbus/tox.ini
Labels: in progress

#929 Use tempfile crate
  Cargo.lock
  Cargo.toml
  src/engine/strat_engine/pool.rs
  src/engine/strat_engine/tests/loopbacked.rs
  src/engine/strat_engine/tests/mod.rs
  src/engine/strat_engine/thinpool/filesystem.rs
  src/engine/strat_engine/thinpool/thinpool.rs
  src/lib.rs
Labels: review-final

#933 Omit a bunch of needless extern declarations
  src/bin/stratisd.rs
  src/engine/strat_engine/engine.rs
  src/engine/strat_engine/tests/real.rs
Labels: review-final, trivial

#943 Make clippy task an allowed failure on Travis
  .travis.yml
Labels: review-final

#941 Update formatting for newest version of yapf
  tests/client-dbus/src/stratisd_client_dbus/_implementation.py
  tests/client-dbus/src/stratisd_client_dbus/_managedobjects.py
Labels: review-final

#940 Have method in StratEngine implementation return StratBlockDevs
  src/engine/strat_engine/backstore/backstore.rs
  src/engine/strat_engine/backstore/blockdevmgr.rs
  src/engine/strat_engine/pool.rs
Labels: review-final

#948 Remove obsoleted allow(dead-code)
  src/engine/strat_engine/tests/real.rs
Labels: review-final, trivial

#935 Attach setting blockdev id to Pool trait
  src/dbus_api/blockdev.rs
  src/engine/engine.rs
  src/engine/sim_engine/blockdev.rs
  src/engine/sim_engine/pool.rs
  src/engine/strat_engine/backstore/backstore.rs
  src/engine/strat_engine/backstore/blockdev.rs
  src/engine/strat_engine/pool.rs
Labels: review-final

#951 Add static header size to test buffer used for BDA::initialize()
  src/engine/strat_engine/backstore/metadata.rs
Labels: review-final, trivial

#950 Change SyncAll::sync_all() to return io::Result
  src/engine/strat_engine/backstore/metadata.rs
Labels: review-final, trivial

#954 Remove some remaining flush() calls in favor of sync_all()
  src/engine/strat_engine/backstore/metadata.rs
  src/engine/strat_engine/device.rs
  src/engine/strat_engine/tests/loopbacked.rs
  src/engine/strat_engine/thinpool/mdv.rs
  src/engine/strat_engine/thinpool/thinpool.rs
Labels: review-final

#956 pub modifier sweep
  src/dbus_api/types.rs
  src/engine/sim_engine/pool.rs
  src/engine/strat_engine/backstore/blockdev.rs
  src/engine/strat_engine/backstore/blockdevmgr.rs
Labels: review-final

#958 Use fallocate() to create backing files for loopback devs
  src/engine/strat_engine/tests/loopbacked.rs
Labels: review-final, trivial

#965 Documentation: Update compiler & fmt versions
  .travis.yml
  README.md
Labels: review-final
