Repository stratis-storage/stratisd, pull requests merged in 2018-04, with the labels that each got.

#873 Reverse order of arguments to block_evaluate
  src/bin/stratisd.rs
  src/engine/engine.rs
  src/engine/sim_engine/engine.rs
  src/engine/strat_engine/engine.rs
Labels: review-final

#866 Generate UML-diagram like graphs for particular modules in stratis
  Makefile
  scripts/uml_graphs.rs
Labels: review-final

#868 Combine EngineError and StratisError
  src/dbus_api/util.rs
  src/engine/engine.rs
  src/engine/errors.rs
  src/engine/macros.rs
  src/engine/mod.rs
  src/engine/sim_engine/engine.rs
  src/engine/sim_engine/pool.rs
  src/engine/strat_engine/backstore/backstore.rs
  src/engine/strat_engine/backstore/blockdev.rs
  src/engine/strat_engine/backstore/blockdevmgr.rs
  src/engine/strat_engine/backstore/cleanup.rs
  src/engine/strat_engine/backstore/device.rs
  src/engine/strat_engine/backstore/metadata.rs
  src/engine/strat_engine/backstore/range_alloc.rs
  src/engine/strat_engine/backstore/setup.rs
  src/engine/strat_engine/backstore/util.rs
  src/engine/strat_engine/cleanup.rs
  src/engine/strat_engine/device.rs
  src/engine/strat_engine/devlinks.rs
  src/engine/strat_engine/dm.rs
  src/engine/strat_engine/engine.rs
  src/engine/strat_engine/pool.rs
  src/engine/strat_engine/thinpool/filesystem.rs
  src/engine/strat_engine/thinpool/mdv.rs
  src/engine/strat_engine/thinpool/thinids.rs
  src/engine/strat_engine/thinpool/thinpool.rs
  src/engine/strat_engine/thinpool/util.rs
  src/stratis/errors.rs
  src/stratis/mod.rs
Labels: review-final

#878 Fix formattting
  src/engine/strat_engine/backstore/metadata.rs
Labels: review-final

#882 Update to new version of clippy
  Cargo.lock
  src/engine/strat_engine/thinpool/thinpool.rs
Labels: review-final

#883 Strip out an allow but keep clippy happy
  src/dbus_api/util.rs
Labels: review-final, trivial

#881 Tidy error handling in device cleanup as much as possible
  src/engine/strat_engine/tests/util.rs
Labels: review-final

#887 Update to new version of clippy
  Cargo.lock
Labels: in progress

#888 Extend a test to verify behavior on non-existent object path
  tests/client-dbus/tests/dbus/manager/test_object_path.py
Labels: review-final

#889 Build with dbus by default
  Cargo.toml
  Makefile
  src/bin/stratisd.rs
  src/dbus_api/api.rs
Labels: review-final

#891 Enable i686 Travis build
  .travis.yml
Labels: review-prelim

#890 Make sure clippy also checks bin/stratisd.rs
  Makefile
  src/bin/stratisd.rs
Labels: review-final
