Repository stratis-storage/stratisd, pull requests merged in 2018-03, with the labels that each got.

#802 SeekFrom::Start() takes bytes as a parameter (not Sectors)
  src/engine/strat_engine/device.rs
Labels: review-final

#801 Add man page for stratisd
  .gitignore
  .travis.yml
  Makefile
  docs/stratisd.txt
Labels: review-final

#789 Add systemd service file
  stratisd.service
Labels: review-final

#806 Store the backstore device in the thinpool
  src/engine/strat_engine/thinpool/thinpool.rs
Labels: review-prelim

#800 Only allow one filesystem to be created at a time.
  src/dbus_api/pool.rs
  tests/client-dbus/tests/dbus/pool/test_create_filesystem.py
Labels: review-final

#788 Add log messages on pool setup fail
  src/engine/strat_engine/engine.rs
Labels: review-final

#809 Have tests that test adding blockdevs check the blockdevs being exported
  tests/client-dbus/tests/dbus/pool/test_add_devs.py
Labels: review-final

#810 When wiping metadev use LinearDev::size() method to specify amount
  src/engine/strat_engine/thinpool/thinpool.rs
Labels: review-final

#813 Update gitignore to ignore some other test directory
  .gitignore
Labels: review-final, trivial

#816 Formalize prerequisites about length of FORMAT_VERSION
  src/engine/strat_engine/dmnames.rs
Labels: review-final

#817 Temporarily do not use get_mount_point in fs snapshot code
  src/engine/strat_engine/thinpool/filesystem.rs
Labels: review-final

#819 Add 0.5 release notes
  README.md
  docs/RELNOTES-0.5.md
Labels: review-final

#821 Update to devicemapper 0.19.0
  Cargo.lock
  Cargo.toml
  src/engine/strat_engine/backstore/backstore.rs
  src/engine/strat_engine/thinpool/thinpool.rs
Labels: review-final

#818 Complete cache development
  src/dbus_api/blockdev.rs
  src/dbus_api/pool.rs
  src/engine/engine.rs
  src/engine/mod.rs
  src/engine/sim_engine/pool.rs
  src/engine/strat_engine/backstore/backstore.rs
  src/engine/strat_engine/backstore/setup.rs
  src/engine/strat_engine/pool.rs
  src/engine/strat_engine/serde_structs.rs
  src/engine/strat_engine/thinpool/filesystem.rs
  src/engine/strat_engine/thinpool/mdv.rs
  src/engine/strat_engine/thinpool/thinpool.rs
  src/engine/types.rs
  tests/client-dbus/src/stratisd_client_dbus/_data.py
  tests/client-dbus/tests/dbus/pool/test_add_cache_devs.py
  tests/client-dbus/tests/dbus/pool/test_add_data_devs.py
Labels: review-final

#825 Correct BDA layout
  src/engine/strat_engine/backstore/metadata.rs
Labels: review-final

#823 version 0.5.0
  Cargo.lock
  Cargo.toml
Labels: review-final

#834 Get rid of a bunch of check() functions that aren't used anymore
  src/engine/engine.rs
  src/engine/macros.rs
  src/engine/sim_engine/engine.rs
  src/engine/sim_engine/pool.rs
  src/engine/strat_engine/engine.rs
  src/engine/strat_engine/pool.rs
Labels: review-final

#836 Add make target to compress stratisd manpage
  .gitignore
  Makefile
Labels: review-final, trivial

#828 Fix fs_usage() for variable-size return values
  src/engine/strat_engine/thinpool/filesystem.rs
Labels: review-final

#840 Remove optional devnode from BlockDevSave
  src/engine/strat_engine/backstore/blockdev.rs
  src/engine/strat_engine/serde_structs.rs
Labels: review-final

#842 Update minimum Rust version
  README.md
Labels: review-final

#844 Get rid of two coverage pragmas
  tests/client-dbus/src/stratisd_client_dbus/_connection.py
Labels: review-final, trivial

#833 Add targets to the Makefile PEP8 compliance
  .travis.yml
  tests/client-dbus/Makefile
  tests/client-dbus/README.rst
  tests/client-dbus/check.py
  tests/client-dbus/requirements.txt
  tests/client-dbus/setup.py
  tests/client-dbus/src/stratisd_client_dbus/__init__.py
  tests/client-dbus/src/stratisd_client_dbus/_connection.py
  tests/client-dbus/src/stratisd_client_dbus/_constants.py
  tests/client-dbus/src/stratisd_client_dbus/_data.py
  tests/client-dbus/src/stratisd_client_dbus/_implementation.py
  tests/client-dbus/src/stratisd_client_dbus/_managedobjects.py
  tests/client-dbus/src/stratisd_client_dbus/_stratisd_constants.py
  tests/client-dbus/tests/dbus/_dm.py
  tests/client-dbus/tests/dbus/_loopback.py
  tests/client-dbus/tests/dbus/_misc.py
  tests/client-dbus/tests/dbus/filesystem/test_rename.py
  tests/client-dbus/tests/dbus/manager/test_create.py
  tests/client-dbus/tests/dbus/manager/test_destroy.py
  tests/client-dbus/tests/dbus/manager/test_object_path.py
  tests/client-dbus/tests/dbus/manager/test_stratis.py
  tests/client-dbus/tests/dbus/pool/test_add_cache_devs.py
  tests/client-dbus/tests/dbus/pool/test_add_data_devs.py
  tests/client-dbus/tests/dbus/pool/test_create_filesystem.py
  tests/client-dbus/tests/dbus/pool/test_destroy_filesystem.py
  tests/client-dbus/tests/dbus/pool/test_rename.py
  tests/client-dbus/tests/dbus/pool/test_udev.py
Labels: review-final

#850 Get rid of a '.'
  tests/client-dbus/Makefile
Labels: review-final, trivial

#857 Make self parameters to Eventable methods non-mut
  src/bin/stratisd.rs
  src/engine/engine.rs
  src/engine/sim_engine/engine.rs
  src/engine/strat_engine/engine.rs
Labels: review-final

#858 Initialize a devicemapper context just once during stratisd execution
  src/bin/stratisd.rs
  src/engine/engine.rs
  src/engine/sim_engine/engine.rs
  src/engine/strat_engine/backstore/backstore.rs
  src/engine/strat_engine/cleanup.rs
  src/engine/strat_engine/dm.rs
  src/engine/strat_engine/engine.rs
  src/engine/strat_engine/mod.rs
  src/engine/strat_engine/pool.rs
  src/engine/strat_engine/tests/util.rs
  src/engine/strat_engine/thinpool/filesystem.rs
  src/engine/strat_engine/thinpool/mdv.rs
  src/engine/strat_engine/thinpool/thinpool.rs
Labels: review-final

#851 Move 1 second sleeps after stratisd setup to setUp function
  tests/client-dbus/tests/dbus/_misc.py
  tests/client-dbus/tests/dbus/filesystem/test_rename.py
  tests/client-dbus/tests/dbus/manager/test_create.py
  tests/client-dbus/tests/dbus/manager/test_destroy.py
  tests/client-dbus/tests/dbus/manager/test_object_path.py
  tests/client-dbus/tests/dbus/manager/test_stratis.py
  tests/client-dbus/tests/dbus/pool/test_add_cache_devs.py
  tests/client-dbus/tests/dbus/pool/test_add_data_devs.py
  tests/client-dbus/tests/dbus/pool/test_create_filesystem.py
  tests/client-dbus/tests/dbus/pool/test_destroy_filesystem.py
  tests/client-dbus/tests/dbus/pool/test_rename.py
Labels: review-final

#864 Abstract the action of setting up a pool
  src/engine/strat_engine/backstore/backstore.rs
  src/engine/strat_engine/backstore/mod.rs
  src/engine/strat_engine/backstore/setup.rs
  src/engine/strat_engine/engine.rs
  src/engine/strat_engine/mod.rs
  src/engine/strat_engine/pool.rs
Labels: review-final
