Repository stratis-storage/stratisd, pull requests merged in 2018-02, with the labels that each got.

#747 Do not forget thin_meta_dev_spare when getting segments for metadata
  src/engine/strat_engine/setup.rs
Labels: bug, review-final

#690 Handle udev add events
  src/bin/stratisd.rs
  src/dbus_api/api.rs
  src/dbus_api/mod.rs
  src/engine/engine.rs
  src/engine/errors.rs
  src/engine/sim_engine/engine.rs
  src/engine/strat_engine/engine.rs
  src/engine/strat_engine/setup.rs
  src/engine/strat_engine/thinpool/util.rs
  src/engine/strat_engine/util.rs
  src/lib.rs
  src/stratis/errors.rs
Labels: review-final

#752 Update to new version of libstratis in Cargo.lock
  Cargo.lock
Labels: review-final

#749 Do not allocate blocks reserved for Stratis metadata
  src/engine/strat_engine/blockdev.rs
  src/engine/strat_engine/blockdevmgr.rs
  src/engine/strat_engine/pool.rs
  src/engine/strat_engine/setup.rs
Labels: bug, review-final

#755 Update stratisd-client-dbus introspection data to match daemon
  tests/client-dbus/src/stratisd_client_dbus/_data.py
Labels: review-final, trivial

#756 Correct use statements
  src/bin/stratisd.rs
  src/dbus_api/api.rs
  src/dbus_api/blockdev.rs
  src/dbus_api/filesystem.rs
  src/dbus_api/pool.rs
  src/dbus_api/util.rs
  src/engine/engine.rs
  src/engine/errors.rs
  src/engine/sim_engine/blockdev.rs
  src/engine/sim_engine/filesystem.rs
  src/engine/sim_engine/pool.rs
  src/engine/sim_engine/randomization.rs
  src/engine/strat_engine/blockdevmgr.rs
  src/engine/strat_engine/cleanup.rs
  src/engine/strat_engine/device.rs
  src/engine/strat_engine/devlinks.rs
  src/engine/strat_engine/metadata.rs
  src/engine/strat_engine/pool.rs
  src/engine/strat_engine/range_alloc.rs
  src/engine/strat_engine/serde_structs.rs
  src/engine/strat_engine/setup.rs
  src/engine/strat_engine/tests/logger.rs
  src/engine/strat_engine/tests/real.rs
  src/engine/strat_engine/tests/util.rs
  src/engine/strat_engine/thinpool/filesystem.rs
  src/engine/strat_engine/thinpool/mdv.rs
  src/engine/strat_engine/thinpool/thinpool.rs
  src/stratis/errors.rs
Labels: review-final

#746 Testing for udev add support
  tests/client-dbus/tests/dbus/_dm.py
  tests/client-dbus/tests/dbus/_loopback.py
  tests/client-dbus/tests/dbus/pool/test_udev.py
Labels: review-final

#678 Rework Table and remove HasName/HasUuid traits
  src/dbus_api/api.rs
  src/dbus_api/blockdev.rs
  src/dbus_api/filesystem.rs
  src/dbus_api/pool.rs
  src/engine/engine.rs
  src/engine/macros.rs
  src/engine/mod.rs
  src/engine/sim_engine/blockdev.rs
  src/engine/sim_engine/engine.rs
  src/engine/sim_engine/filesystem.rs
  src/engine/sim_engine/pool.rs
  src/engine/strat_engine/blockdev.rs
  src/engine/strat_engine/blockdevmgr.rs
  src/engine/strat_engine/cleanup.rs
  src/engine/strat_engine/devlinks.rs
  src/engine/strat_engine/engine.rs
  src/engine/strat_engine/pool.rs
  src/engine/strat_engine/thinpool/filesystem.rs
  src/engine/strat_engine/thinpool/mdv.rs
  src/engine/strat_engine/thinpool/thinpool.rs
  src/engine/structures.rs
  src/engine/types.rs
Labels: review-final

#770 Export BlockDevState in engine module API
  src/dbus_api/blockdev.rs
  src/engine/mod.rs
Labels: review-final, trivial

#772 Refactor to use linear device to represent backstore
  src/engine/strat_engine/backstore/backstore.rs
  src/engine/strat_engine/backstore/blockdev.rs
  src/engine/strat_engine/backstore/blockdevmgr.rs
  src/engine/strat_engine/backstore/cleanup.rs
  src/engine/strat_engine/backstore/device.rs
  src/engine/strat_engine/backstore/metadata.rs
  src/engine/strat_engine/backstore/mod.rs
  src/engine/strat_engine/backstore/range_alloc.rs
  src/engine/strat_engine/backstore/setup.rs
  src/engine/strat_engine/backstore/util.rs
  src/engine/strat_engine/cleanup.rs
  src/engine/strat_engine/device.rs
  src/engine/strat_engine/dmnames.rs
  src/engine/strat_engine/engine.rs
  src/engine/strat_engine/mod.rs
  src/engine/strat_engine/pool.rs
  src/engine/strat_engine/serde_structs.rs
  src/engine/strat_engine/thinpool/mod.rs
  src/engine/strat_engine/thinpool/thinids.rs
  src/engine/strat_engine/thinpool/thinpool.rs
Labels: review-final

#778 Move definition of DEV_PATH to a more central location than devlinks file
  src/engine/strat_engine/devlinks.rs
  src/engine/strat_engine/engine.rs
  src/engine/strat_engine/thinpool/mdv.rs
Labels: review-final

#781 Add another possiblity to the CacheRoles
  src/engine/strat_engine/backstore/backstore.rs
  src/engine/strat_engine/dmnames.rs
Labels: review-final

#783 Update devicemapper dependency to 0.17.1
  Cargo.lock
  Cargo.toml
  src/engine/strat_engine/backstore/setup.rs
  src/engine/strat_engine/tests/util.rs
  src/engine/strat_engine/thinpool/filesystem.rs
  src/engine/strat_engine/thinpool/mdv.rs
Labels: review-final

#793 Handle change in blockdev size on setup
  src/engine/strat_engine/backstore/backstore.rs
  src/engine/strat_engine/backstore/blockdev.rs
  src/engine/strat_engine/backstore/blockdevmgr.rs
  src/engine/strat_engine/backstore/setup.rs
Labels: review-final

#785 Set Dm UUID fields when creating devices
  src/engine/strat_engine/backstore/backstore.rs
  src/engine/strat_engine/dmnames.rs
  src/engine/strat_engine/thinpool/filesystem.rs
  src/engine/strat_engine/thinpool/thinpool.rs
Labels: review-final

#797 Update to new version of clippy
  Cargo.lock
  src/engine/strat_engine/thinpool/filesystem.rs
Labels: in progress

#796 Remove an obsoleted comment
  src/engine/strat_engine/backstore/backstore.rs
Labels: review-final, trivial

#799 Add a clarifying comment to Pool::blockdevs
  src/engine/engine.rs
Labels: review-final, trivial
